package my.epi.redditech.model.api

data class SubredditModel (
    val accept_followers: Boolean,
    val banner_img: String,
    val banner_size: List<Int>?,
    val coins: Int,
    val default_set: Boolean,
    val description: String,
    val disable_contributor_requests: Boolean,
    val display_name: String,
    val display_name_prefixed: String,
    val free_form_reports: Boolean,
    val header_img: String?,
    val header_size: List<Int>?,
    val icon_color: String,
    val icon_img: String,
    val icon_size: List<Int>,
    val is_default_banner: Boolean,
    val is_default_icon: Boolean,
    val key_color: String,
    val link_flair_enabled: Boolean,
    val link_flair_position: String,
    val name: String,
    val over_18: Boolean,
    val primary_color: String,
    val public_description: String,
    val restrict_commenting: Boolean,
    val restrict_posting: Boolean,
    val show_media: Boolean,
    val submit_link_label: String,
    val submit_text_label: String,
    val subreddit_type: String,
    val subscribers: Int,
    val title: String,
    val url: String,
    val user_is_subscriber: Boolean
)